[package]
name = "block_pool"
description = "Object pool that blocks when waiting for an object."
version = "0.1.2"
edition = "2018"
authors = ["Shelby Doolittle <shelby@shelbyd.com>"]
license = "MIT"
repository = "https://github.com/shelbyd/block_pool"

[dependencies]
